### ISSUE TITLE
[feature request] disallow submission of, or drop already submitted lines

### ISSUE THREAD

**Issue by thasti** [c3subtitles/L2S2#108]
Sometimes, if two people type the same part of a sentence and press enter at nearly the same time, the same line is displayed on the subtitle screen twice - which is a bad thing considering there are only ~3 lines on the talk screens.

Suggestion:
This could be avoided by stopping doubly-typed lines (calculate levensthein distance and compare length) from appearing.  IMO the best way of handling this would be checking silently dropping the double submissions (they wont appear in the history & on the screens after hitting enter, but the input line clears as if it was sent).

**Comment by marudor** [comment]
Wont do. The more feasible approach would probably be improvement of the preview lines.
I want the subtitlers do decide what to publish and what not.
The Software is there to help them doing it. There is a seperate issue about that.
