### ISSUE TITLE
Role definitions

### ISSUE THREAD

**Issue by percidae** [c3subtitles/L2S2#17]
Definition of different user roles:

Admin: Everything, if entering a speech-input-logged room choose which role. Also log normal rooms, maybe with the possibility to invite other users. (Use-case: several Schriftdolmetscher)

Normal User: Only typing in the normal user-mode

Speech corrector: Enter a in the "speech-recognition mode" locked room as corrector. (Does not necessarily need to be reduced to only one person per speech input). Also lock the room for speech-input only, but stay in there as corrector. Also act as normal user in the typing mode.

Speech input: Enter a room and lock it in "speech recognition mode" as speech-input role. Also act as normal  user in the typing mode.

**Comment by percidae** [comment]
On the congress we saw that is makes sense if every "normal" user is also able to do the corrections if there is speech input with a lock on that room in progress. So this role can be ignored.

**Comment by Ryuno-Ki** [comment]
Noticed.

**Comment by marudor** [comment]
Done.
