### ISSUE TITLE
Keep an eye on a11y

### ISSUE THREAD

**Issue by Ryuno-Ki** [c3subtitles/L2S2#28]
Accessibility is important.

At least, we should markup live regions in _read.html_ (since this site can be browsed to by mobiles, if I got that right) to enable screenreaders to read the content. For example, if you are blind and couldn't attend 31C3

Webkrauts [reported about live reiongs](http://webkrauts.de/artikel/2014/ein-attribut-fuer-eine-live-region) recently (German).

**Comment by percidae** [comment]
There should be one output via the web which is usable for a braille output for deaf-blind users.
For the output there should be more choices anyway, but I will create another issue for that.

**Comment by Ryuno-Ki** [comment]
@percidae Can you refer to this id (28) in the other issue? This way, GitHub will create a link.

**Comment by marudor** [comment]
React a11y will cover this.
