### ISSUE TITLE
Auto-color

### ISSUE THREAD

**Issue by patrickhanft** [c3subtitles/L2S2#39]
Font color should not depend on the setting of the user, but be assigned by the hall interface. Goal is to suppress too similar font colors of different users.

**Comment by percidae** [comment]
There should not be a person assigning the colours. The colours should be applied depending on the order in which you entered the room to have the best possible differences to distinguish among the users.
So a user does not have it's own colour but gets one assigned when he enters a room.
We had the problem that there were to many similar colors you couldn't distinguish very well and the user could not change them themselfes.

**Comment by Ryuno-Ki** [comment]
What about defining a colour palette (for example using [ColorBrewer](http://colorbrewer2.org/)) and assign them peu a peu to new writers of a room?

In average, how many writers are there per room? How many max?

**Comment by patrickhanft** [comment]
Yes, this was the idea. But the colors should be well-distinguishable and not “similar, to fit beautifully into a design” (at least, that is the first idea I have looking at ColorBrewer).

Typically, there are about three to five active writer in a room. But especially if there are more than one speaker, it's sometimes useful to have teams of writers specifically assigned to a speaker and therefore have more people in the room. 

Aditionally we sometimes have people in the room not actually participating in the writing, but doing supervision, or being spare writers to relieve others or let them have a break. Up to 10 people is possible. 

To that there is the possibility of being twice in a room (having been connected to wifi first, but then to LAN) or even (in emergency case) having an account shared, so two people are writing with the same user name.

So I think it would be not a very good idea to have a fix technical limit here …

**Comment by Ryuno-Ki** [comment]
Hit diverging on the site ;-)

It's meant for colouring maps. Therefore, the colours are usually sequential.

**Comment by patrickhanft** [comment]
Okay. Yeah, you'd have to take out the bright colors and have an algorithm choose a color with big distance to the previous choice. (But still I'm in doubt about the few colors you can choose at max)

**Comment by patrickhanft** [comment]
Maybe use the ones in „qualitative“, choose 12 data classes, throw yellowish away, make all a bit more darker and than order them to have big differences to the previous color :-)
