### ISSUE TITLE
Backen Rewrite, Cluster Socketcluster.io

### ISSUE THREAD

**Issue by marudor** [c3subtitles/L2S2#45]

**Comment by Ryuno-Ki** [comment]
[SC](http://socketcluster.io/) sounds good, but is it reliable yet?

To me, it looks like it isn't [even a year old](https://github.com/TopCloud/socketcluster/graphs/code-frequency) and merely [maintained by one author](https://github.com/TopCloud/socketcluster/graphs/contributors).

**Comment by marudor** [comment]
Yeah - it is reliable though.
Still, gonna use primus instead. (Using it at work as well)
