### ISSUE TITLE
Frontend Re-Design

### ISSUE THREAD

**Issue by percidae** [c3subtitles/L2S2#47]
It would be nice if every frontend-user who only watches the subtitles could configure the design for themselves like in the commercial product "streamtext.net".

The screenshots are: a smaller view: you can see the "scroll" Button ist not visible and a wide view in high contrast setting.
![screenshot_small](https://cloud.githubusercontent.com/assets/5713994/8021210/1012b89a-0c97-11e5-9220-1d43f9e23df1.jpg)
![screenshot_wide_high_contrast](https://cloud.githubusercontent.com/assets/5713994/8021211/15a2b6f2-0c97-11e5-97d8-359a65f4572d.jpg)

You can choose:
Themes:
  * Custom (maybe saved with coockies?)
  * High contrast: BG Black, Text colour: Yellow
  * Terminal: BG: Green: TC: Lime
  * Notepad: BG: Yellow TC: Black
  * Green & Gold: BG: Green TC: Yellow
  * Sunrise: BG: Dark Blue TC: Yellow
  * Default: BG: White TC: Black

Font Size:
14, 18, 24, 30, 36, 42, 48, 54, 60, 72, 84, 96 

Font Family:
Arial, Comic, Courier New, Helvetica, Tahoma, Trebuchet, Verdana

Background:
White, Dark Blue, Blue, Green, Dark Cyan, Lime, Aqua, Olive, Gray, Dark Red, Silver, Red, Fuchsia, Yellow, White

Text Color:
Black, Dark Blue, Green, Dark Cyan, Lime, Aqua, Olive, Gray, Dark Red, Silver, Red, Fuchsia, Yellow, White

Language:
(Maybe a future feature?)

Scroll:
yes/no

**Comment by Ryuno-Ki** [comment]
As long as this is not free text input (XSS vulnerability), it should be pretty easy to define several styles and control them via HTML classes.

Concerning language, where shall the i18n happen: Server side or Client side?
Where is the translation managed (e.g. on Transifex) ?
